#############################################################################
# Makefile for building: ants
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  ants.pro
# Template: app
# Command: /home/gui/Qt/5.3/gcc_64/bin/qmake -o Makefile ants.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../Qt/5.3/gcc_64/mkspecs/linux-g++ -I. -I/usr/include/SDL2
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/gui/Qt/5.3/gcc_64
LIBS          = $(SUBLIBS) -lSDL2 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/gui/Qt/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Case.cpp \
		Grille.cpp \
		Ant.cpp 
OBJECTS       = main.o \
		Case.o \
		Grille.o \
		Ant.o
DIST          = ../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		../Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		ants.pro main.cpp \
		Case.cpp \
		Grille.cpp \
		Ant.cpp
QMAKE_TARGET  = ants
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = ants


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ants.pro ../Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf ../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		../Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		ants.pro
	$(QMAKE) -o Makefile ants.pro
../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../Qt/5.3/gcc_64/mkspecs/common/unix.conf:
../Qt/5.3/gcc_64/mkspecs/common/linux.conf:
../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../Qt/5.3/gcc_64/mkspecs/common/g++-base.conf:
../Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf:
../Qt/5.3/gcc_64/mkspecs/qconfig.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf:
../Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf:
../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf:
../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../Qt/5.3/gcc_64/mkspecs/features/default_post.prf:
../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf:
../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf:
../Qt/5.3/gcc_64/mkspecs/features/yacc.prf:
../Qt/5.3/gcc_64/mkspecs/features/lex.prf:
ants.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ants.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/ants1.0.0 || mkdir -p .tmp/ants1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/ants1.0.0/ && (cd `dirname .tmp/ants1.0.0` && $(TAR) ants1.0.0.tar ants1.0.0 && $(COMPRESS) ants1.0.0.tar) && $(MOVE) `dirname .tmp/ants1.0.0`/ants1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ants1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp Grille.h \
		Case.h \
		Ant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Case.o: Case.cpp Case.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Case.o Case.cpp

Grille.o: Grille.cpp Grille.h \
		Case.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Grille.o Grille.cpp

Ant.o: Ant.cpp Ant.h \
		Grille.h \
		Case.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ant.o Ant.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

